server:
  port: 9001
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: springcloud-app
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: idea-springcloud
    sentinel:
      transport:
        # 配置 Sentinel Dashboard 的地址
        dashboard: localhost:8080
        # 默认8719 ，如果端口被占用，端口号会自动 +1，提供给 sentinel 的监控端口
        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.kstart.springcloud.entities  # 所有Entity 别名类所在包
  
management:
  endpoints:
    web:
      exposure:
        include: '*'  
#eureka:
#  client:
#    # 注册进 Eureka 的服务中心
#    register-with-eureka: true
#    # 检索 服务中心 的其它服务
#    fetch-registry: true
#    service-url:
#      # 设置与 Eureka Server 交互的地址
#      defaultZone: http://localhost:7001/eureka/